apiVersion: v1
kind: ReplicationController
metadata:
  name: orchestrator
  labels:
    service: orchestrator
    component: backend
spec:
  replicas: 1
  selector:
    service: orchestrator
    component: backend
  template:
    metadata:
      labels:
        service: orchestrator
        component: backend
    spec:
      containers:
      - name: orchestrator
        image: albertobrigandi/orchestrator:latest
        imagePullPolicy: Always
        env:
          - name: ORCHESTRATOR_DB_ENDPOINT
            value: 'orchestrator-database:3306'
          - name: ORCHESTRATOR_DB_USER
            value: orchestrator
          - name: ORCHESTRATOR_DB_PWD
            value: password
          - name: WORKFLOW_DB_ENDPOINT
            value: 'workflow-database:3306'
          - name: WORKFLOW_DB_USER
            value: orchestrator
          - name: WORKFLOW_DB_PWD
            value: password
        ports:
        - containerPort: 8080
